name: Build Kernel with KernelSU & SUSFS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+rx ~/bin/repo
          echo "~/bin" >> $GITHUB_PATH

      - name: Clone mkbootimg repository
        run: |
          git clone https://android.googlesource.com/platform/system/tools/mkbootimg
          echo "MKBOOTIMG_DIR=$(pwd)/mkbootimg" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install --upgrade pip

      - name: Verify mkbootimg.py
        run: |
          source $GITHUB_ENV
          python3 $MKBOOTIMG_DIR/mkbootimg.py --help > /dev/null || echo "mkbootimg.py is ready for use"

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.GITLAB_SSH_KEY }}' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh -o StrictHostKeyChecking=no git@ssh.gitlab.hentaios.com -p 2052

      - name: Run Kernel Build Script
        run: |
          source $GITHUB_ENV
          chmod 755 build_kernel.sh
          ./build_kernel.sh

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-kernel
          path: |
            ./builds/**/*.img
            ./builds/**/*.zip
