name: Build Kernel with KernelSU & SUSFS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Set Up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc curl git repo gcc-aarch64-linux-gnu bison flex make zip unzip patch

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.GITLAB_SSH_KEY }}' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keygen -R ssh.gitlab.hentaios.com

      - name: Run Kernel Build Script
        run: |
          chmod 755 build_kernel.sh
          ./build_kernel.sh

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-kernel
          path: |
            ./builds/**/*.img
            ./builds/**/*.zip
