name: Build Kernel with KernelSU & SUSFS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 32768
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod 755 ~/bin/repo
          echo "~/bin" >> $GITHUB_PATH

      - name: Set up SSH for HentaiOS GitLab
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.GITLAB_SSH_KEY }}' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519
          
          ssh -o StrictHostKeyChecking=no git@ssh.gitlab.hentaios.com -p 2052

      - name: Clone HentaiOS kernel source
        run: |
          mkdir -p ./builds/kernel
          cd ./builds/kernel
          repo init --depth=1 -u https://gitlab.hentaios.com/hentaios-gs-6.x/manifest.git/ -b Vallhound
          repo --trace sync -c --no-tags --fail-fast -v -j$(nproc --all) --force-sync

      - name: Apply KernelSU-Next patches
        run: |
          cd ./builds/kernel/aosp
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next

          cd ./KernelSU-Next
          version=$(expr 10000 + $(git rev-list --count HEAD) + 200)
          echo "KernelSU-Next version: $version"
          sed -i "s/ccflags-y += -DKSU_VERSION=.*/ccflags-y += -DKSU_VERSION=$version/" ./kernel/Makefile

      - name: Apply SUSFS patches
        run: |
          cd ./builds
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "gki-android14-6.1"
          
          cp ./susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./kernel/aosp/KernelSU-Next/
          cp ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./kernel/aosp/
          cp ./susfs4ksu/kernel_patches/fs/* ./kernel/aosp/fs/
          cp ./susfs4ksu/kernel_patches/include/linux/* ./kernel/aosp/include/linux/
          cd ./kernel/aosp/KernelSU-Next
          patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
          cd ../
          patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true

      - name: Add sidex's patches
        run: |
          cp Implement-SUSFS-v1.5.4-for-KernelSU-Next.patch ./builds/kernel/aosp/KernelSU-Next/
          cd ./builds/kernel/aosp/KernelSU-Next/
          patch -p3 < Implement-SUSFS-v1.5.4-for-KernelSU-Next.patch

      - name: Set KernelSU and SUSFS config
        run: |
          cd ./builds/kernel/aosp
          
          perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Sat Apr 20 04:20:00 UTC 2024"}' ./scripts/mkcompile_h
          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ../build/kernel/kleaf/impl/stamp.bzl


      - name: Build Kernel For Raviole
        run: |
          cd ./builds/kernel
          exec tools/bazel run \
              --kernel_package=@//aosp \
              --verbose_failures \
              --lto=full \
              --config=stamp \
              --config=raviole \
              //private/devices/google/raviole:gs101_raviole_dist "$@"

      - uses: actions/upload-artifact@v4
        with:
          name: kernel-raviole
          path: ./builds/kernel/out/raviole/dist/*.img
